# Generated by Django 4.2.15 on 2024-08-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='post',
            field=models.CharField(blank=True, choices=[('OKK', 'OKK'), ('GPH', 'GPH'), ('Admin', 'Admin'), ('Operator', 'Operator')], max_length=20, null=True, verbose_name='Должность'),
        ),
    ]
