# Generated by Django 4.2.15 on 2024-09-16 13:45

from django.db import migrations, models
import exam.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_exam', models.DateField(validators=[exam.models.validate_date_exam], verbose_name='Дата зачета')),
                ('name_intern', models.CharField(max_length=60, validators=[exam.models.validate_name_intern], verbose_name='Фамилия Имя стажера')),
                ('training_form', models.CharField(choices=[('ВО', 'ВО'), ('Универсал', 'Универсал')], max_length=60, verbose_name='Форма обучения')),
                ('try_count', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)], verbose_name='Попытка')),
                ('time_exam', models.TimeField(blank=True, default='00:00', verbose_name='Время зачета')),
                ('result_exam', models.CharField(blank=True, choices=[('Не допущен', 'Не допущен'), ('Допущен', 'Допущен'), ('Неявка', 'Неявка'), ('Отмена', 'Отмена'), ('Не состоялось', 'Не состоялось')], default='', max_length=25, verbose_name='Результат')),
                ('comment_exam', models.TextField(blank=True, max_length=2000, verbose_name='комментарий')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Зачет',
                'verbose_name_plural': 'Зачеты',
            },
        ),
    ]
