# Generated by Django 4.2.15 on 2024-09-09 08:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('date_exam', 'time_exam', 'name_examiner')},
        ),
    ]
