# Generated by Django 4.2.15 on 2024-08-21 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'Зачет', 'verbose_name_plural': 'Зачеты'},
        ),
    ]
