# Generated by Django 4.2.15 on 2024-08-31 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='name_examiner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ФИ сотрудника'),
        ),
    ]
