# Generated by Django 4.2.15 on 2024-09-08 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0003_alter_exam_name_examiner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='date_exam',
            field=models.DateField(error_messages={'blank': 'Пожалуйста, заполните поле даты', 'invalid': 'Пожалуйста, введите дату в формате YYYY-MM-DD', 'null': 'Пожалуйста, заполните поле даты'}, verbose_name='Дата зачета'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='name_examiner',
            field=models.ForeignKey(blank=True, limit_choices_to={'post': 'OKK'}, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ФИ сотрудника'),
        ),
    ]
