# Generated by Django 4.2.15 on 2024-09-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_exam_date_exam_alter_exam_name_examiner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='date_exam',
            field=models.DateField(verbose_name='Дата зачета'),
        ),
    ]
